---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sadh-back-deployment
  namespace: ${DEPLOY_NAMESPACE}
  labels:
    app: sadh
    tier: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sadh
      tier: back
  template:
    metadata:
      labels:
        app: sadh
        tier: back
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sadh_${DEPLOY_ENV}"
        vault.hashicorp.com/agent-inject-template-env: | # Writes at /vault/secrets/env
          {{ with secret "kv/data/sadh_${DEPLOY_ENV}" -}}
            MONGODB_PASSWORD="{{ .Data.data.mongodb_password }}"
            MATRIX_PASSWORD="{{ .Data.data.matrix_password }}"
            DOCUMENSO_TOKEN="{{ .Data.data.documenso_api_token }}"
            DOLIBARR_API_TOKEN="{{ .Data.data.dolibarr_api_token }}"
            SENDER_EMAIL_PASSWORD="{{ .Data.data.sender_email_password }}"
            STARLETTE_SESSION_SECRET="{{ .Data.data.starlette_session_secret }}"
            OIDC_CLIENT_SECRET="{{ .Data.data.oidc_client_secret }}"
            OIDC_ADMIN_CLIENT_SECRET="{{ .Data.data.oidc_admin_client_secret }}"
            OVH_APPLICATION_KEY="{{ .Data.data.ovh_application_key }}"
            OVH_APPLICATION_SECRET="{{ .Data.data.ovh_application_secret }}"
            OVH_CONSUMER_KEY="{{ .Data.data.ovh_consumer_key }}"
          {{- end }}
    spec:
      serviceAccountName: sadh-back-ksa
      containers:
      - name: sadh-back-container
        image: $BACK_IMAGE_TAG
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: DEPLOY_ENV
          value: "${DEPLOY_ENV}"
        - name: VAULT_ROLE_NAME
          value: "sadh_${DEPLOY_ENV}"
      imagePullSecrets:
       - name: gitlab-registery-credentials
